# Site settings
title: Turret
email: scottdj@bigfish.tv
description: Turret is a responsive front-end framework for accessible and semantic website development.Turret defines base styles for all HTML5 native web elements and includes a simple and intuitive grid system for rapid responsive website development
baseurl: /docs # the subpath of your site, e.g. /blog
url: http://scottdejonge.github.io # the base hostname & protocol for your site

# Permalinks
permalink: pretty

# Syntax Highlighter
highlighter: rouge

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
